# Generated by Django 6.0.6 on 2026-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=16)),
                ('mode', models.CharField(max_length=32)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
