# Generated by Django 6.0.6 on 2026-06-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_requestlog_post_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='native_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
