# Generated by Django 6.0.6 on 2026-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_post_native_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.CharField(default='Direct API', max_length=50),
        ),
    ]
