# Generated by Django 6.0.6 on 2026-06-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_post_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
